expected_output = { 
    'con0/0/CPU0': {'conns': 0,
                    'current_user': False,
                    'idle': '00:12:36',
                    'service': 'hardware',
                    'user': 'pyats'},
    'vty0': {'conns': 0,
            'current_user': False,
            'idle': '00:11:45',
            'location': '10.0.0.53',
            'service': 'ssh',
            'user': 'pyats'},
    'vty1': {'conns': 0,
            'current_user': False,
            'idle': '00:12:38',
            'location': '10.0.0.54',
            'service': 'ssh',
            'user': 'cisco'},
    'vty2': {'conns': 0,
            'current_user': False,
            'idle': '00:12:37',
            'location': '10.0.0.55',
            'service': 'ssh',
            'user': 'pyats'},
    'vty3': {'conns': 0,
            'current_user': True,
            'idle': '00:00:00',
            'location': '10.0.0.56',
            'service': 'ssh',
            'user': 'cisco'}
    }
